# We do not need sudo - switch to Docker http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: android

android:
  components:
    - build-tools-22.0.1
    - android-21
    - android-10
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

env:
  global:
    - secure: "VgzgkHpv8GQtVighZP+Fnkeaj08Abk8c+HJePEkO+0c1aoeL0Lwt6yUwXrMlPhgBndLi9foDZV1PH1xVxLlnj5u5GA8hNoNY4cOxjvEpD3E9MQ0gsdKmclMsoodJpY6YQ67FMexW6IVOHxkHcbEFm7ylcobmhyyX+MHujir980s="
    - secure: "GdbZFkBJYt7nuAg8VJytyFFwW/HPpH/kcXXtdjH7Dw5dF/rw1QlBkMCrzVPYv1QgaBW6eprdWQ1OeSi8A4puK/jMGyAxcLVjmop1167MUQjt1C9HuY1HjMiwCrTpbdHchPSQd37cg++sbJ9AXaKdfRxLZ/knMKLtcH/p8d8DHWQ="
  matrix:
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-10 ANDROID_ABI=armeabi

before_install:
  - export TERM=dumb

  # Create and run emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI || exit 1
  - emulator -avd test -no-skin -no-audio -no-window &

install:
  - ./gradlew assemble

script:
  # JavaVM tests
  - ./gradlew --continue check
  # Android tests
  - android-wait-for-emulator || exit 1
  - adb shell input keyevent 82 &
  - ./gradlew --continue -PpreDex=false clean :async:conCheck :async-rx:conCheck

after_success:
  - chmod +x scripts/deploy_to_maven.sh
  - ./scripts/deploy_to_maven.sh
  - ./gradlew integrationTest
